---
- name: setting the loop veriable
  set_fact:
   server_instances:
    - name: 'app1'
      meta:
       group: 'app_servers'
       deployment_name: 'QA'
      security_groups: 'apps'
    - name: 'app2'
      meta:
       group: 'app_servers'
       deployment_name: 'dev'
      security_groups: 'apps'
    - name: 'db'
      meta:
       group: 'database_servers'
       deployment_name: 'dev'
      security_groups: 'db'
    - name: 'frontend'
      meta:
       group: 'load_balancers'
       deployment_name: 'dev'
      security_groups: 'frontend'

- debug:
   var:
    server_instances

- name: set the state of servers
  set_fact:
    state_servers: 'present'

- name: create OpenStack instances
  os_server:
   name: "{{ item.name }}"
   state: "{{ state_servers }}"
   image: "{{ item.image | default('rhel-7.6') }}"
   key_name: "{{ item.key_name | default('ansible_ssh_key') }}"
   flavor: "{{ item.flavor | default('m2.medium') }}"
   meta:
    group: "{{ item.meta.group }}"
    deployment_name: "{{ item.meta.deployment_name }}"
   security_groups: "{{ item.security_groups | default('apps')}}"
   delete_fip: true
   nics:
    - net-name: 'int_network'
   userdata: "{{ lookup('file', 'user_data') }}"
  loop: "{{ server_instances }}"

- when: state_servers == 'present'
  name: assigning floating ip to instances
  os_floating_ip:
   cloud: openstack
   state: present
   server: "{{ item.name }}"
   network: ext_network
   wait: true
   timeout: 200
  loop: "{{ server_instances }}"

    
    
